import Head from 'next/head'
import {getSession} from "next-auth/react";
import {GetServerSideProps} from "next";
import Navbar from "@/components/Navbar";
import useSocket from "@/hooks/useSocket";

export default function Home() {
  useSocket();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
      </main>
    </>
  )
}

export const getServerSideProps:GetServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }

  return {
    props: {
      session
    }
  }
}


